In [30]:
import numpy as np
from numpy.linalg import inv 

def estimate_beta(x, y):
    xtx_i = np.linalg.inv(np.dot(x.T,x)) 
    xtx_ixt = np.dot(xtx_i,x.T)
    beta_hat = np.dot(xtx_ixt,y)
    return beta_hat

- 함수 정의시, 최대한 간단하게 한줄로 무리해서 정의하려니 에러나서 차근차근 계산함...

In [29]:
x.T

array([[1, 1, 1],
       [0, 2, 3],
       [1, 3, 8]])

In [25]:
#x행렬에 intercept를 추가해야함
x = np.array([ [1, 0, 1],
               [1, 2, 3],
               [1, 3, 8]]) #3x3
y = np.transpose(np.array([1, 3, 7])) #3x1

In [26]:
x

array([[1, 0, 1],
       [1, 2, 3],
       [1, 3, 8]])

In [27]:
y

array([1, 3, 7])

In [31]:
estimate_beta(x,y)

array([0.25, 0.25, 0.75])

In [8]:
#sklearn은 디폴트로 intercept가 fit되므로, 데이터에 intercept가 포함된 경우는 fit_intercept=False로 해야함

In [32]:
from sklearn.linear_model import LinearRegression

In [33]:
reg = LinearRegression(fit_intercept=False).fit(x, y)

In [34]:
reg.coef_

array([0.25, 0.25, 0.75])