In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import confusion_matrix


#IRIS 데이터 로드
iris =  sns.load_dataset('iris') 
X= iris.iloc[:,:4] #학습할데이터
y = iris.iloc[:,-1] #타겟
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
5         setosa
6         setosa
7         setosa
8         setosa
9         setosa
10        setosa
11        setosa
12        setosa
13        setosa
14        setosa
15        setosa
16        setosa
17        setosa
18        setosa
19        setosa
20        setosa
21        setosa
22        setosa
23        setosa
24        setosa
25        setosa
26        setosa
27        setosa
28        setosa
29        setosa
         ...    
120    virginica
121    virginica
122    virginica
123    virginica
124    virginica
125    virginica
126    virginica
127    virginica
128    virginica
129    virginica
130    virginica
131    virginica
132    virginica
133    virginica
134    virginica
135    virginica
136    virginica
137    virginica
138    virginica
139    virginica
140    virginica
141    virginica
142    virginica
143    virginica
144    virginica
145    virginica
146    virginica
147    virgini

In [5]:
iris.head(2)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [6]:
# 타겟의 분류 종류 살펴보기
iris.iloc[:,-1].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [7]:
scal = StandardScaler() #scaling
X = scal.fit_transform(X)

In [12]:
### print(y)

In [8]:
# One Versus Rest 구현을 위해 class가 0인것과 아닌것을 구분하기위한 machine class가 1인것과 아닌 것을 구분하기 위한 머신 등을 미리만들어줌
svm_1 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_2 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_3 = SVC(kernel ='rbf', C = 5, gamma = 5)

In [9]:
from sklearn.model_selection import train_test_split #테스트/트레인 데이터로 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [10]:
y_train = pd.get_dummies(y_train) #one hot encoding을 먼저해보자

In [11]:
y_train.head(3)

setosa  versicolor  virginica
110       0           0          1
69        0           1          0
148       0           0          1

In [12]:
svm_1.fit(X_train,y_train.iloc[:,0]) # 데이터 클레스가 0인 애인지 아닌지 구분해주는 머신
svm_2.fit(X_train,y_train.iloc[:,1]) # 데이터 클레스가 1인 애인지 아닌지 구분해주는 머신
svm_3.fit(X_train,y_train.iloc[:,2]) # 데이터 클레스가 2인 애인지 아닌지 구분해주는 머신

print(svm_1.predict(X_test)) #데이터 클래스가 0인지 아닌지 구분해주는 애를 통해서 테스트데이터의 클래스가 0인지 0이 아닌인지 예측해보자

print(svm_1.decision_function(X_test)) #decision_function hyperplane과의 거리를 구하는 방법 필요하다면 활용해주세요

[0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0]
[-1.12470845 -0.86326953 -0.65281099 -0.50248821 -0.76284323 -0.87465573
  1.07709345 -0.99281647  0.47441336 -0.99842743 -0.83989348  0.15633457
  0.32871788 -0.97965464 -0.72385083 -0.92638376  1.28322481 -0.56240455
 -0.72719892 -0.99509775  0.43166724 -0.96451557 -0.82991366 -1.03020581
 -0.75166835  1.13461335  0.39943974 -1.04194106 -0.93376548 -1.06133798]


In [13]:
# 부호가 모든 같은 경우가 있는가? 모두 동점인 경우가 생길것이다.
for i in range(len(X_test)):
    # ~. decision_function을 이용하면 해당 데이터가 하이퍼플레인으로부터 얼마나 떨어져있는 지 거리가 나온다 다음은 그 값의 부호를 이용해
    # 모두가 동점인 경우가 있는지 출력하는 함수 
    if (np.sign(svm_1.decision_function(X_test)[i]) == np.sign(svm_2.decision_function(X_test)[i])) and (np.sign(svm_2.decision_function(X_test)[i]) == np.sign(svm_3.decision_function(X_test)[i])):
        print(i)
        # np.sign 은 부호 계산 함수-> +는 1, -는 -1

3
17
18


In [9]:
## Case 1 : One vs Rest SVM을 이부분에 구현해주세요 위 결과들을 이용해서 multi class SVM을 직접 구현해주세요! 하드코딩이 하시기 편할겁니다.


['versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica', 'virginica', 'setosa', 'virginica', 'setosa', 'versicolor', 'virginica', 'setosa', 'setosa', 'virginica', 'versicolor', 'versicolor', 'setosa', 'versicolor', 'virginica', 'virginica', 'setosa', 'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa', 'setosa', 'virginica', 'virginica', 'versicolor']


0.8666666666666667

In [57]:
print(svm_1.predict(X_test))
print(svm_2.predict(X_test))
print(svm_3.predict(X_test))

[0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0]
[1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1]
[0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0]


In [81]:
def svm_multi(a):
    # 각각의 SMV 머신으로 돌린 예측값 분류
    svm_p1 = svm_1.predict(a)    # ndarray
    svm_p2 = svm_2.predict(a)
    svm_p3 = svm_3.predict(a)
    distinct1 = svm_1.decision_function(a)
    distinct2 = svm_2.decision_function(a)
    distinct3 = svm_3.decision_function(a)
    
    # 예측값으로 만든 데이터 프레임
    multi_class = pd.DataFrame({'setoca':svm_p1,'versicolor':svm_p2,'virginica':svm_p3})
  
    # 예측값 중에 동률 발생시 승자 결정 방법 -> decision_function으로 가장 가까운 클래스로 분류
    for i in range(len(a)):
        if (np.sign(distinct1[i]) == np.sign(distinct2[i])) and (np.sign(distinct2[i]) == np.sign(distinct3[i])):
            winner = (min(abs(distinct1[i]),abs(distinct2[i]),abs(distinct3[i])))
            
            # 가장 가까운 거리의 클래스로 분류
            if winner in abs(distinct1):
                multi_class['setoca'][i] = 1
            elif winner in abs(distinct2):
                multi_class['versicolor'][i] = 1
            else:
                multi_class['virginica'][i] = 1      
    return multi_class

In [83]:
svm_multi(X_test).head(5)

setoca  versicolor  virginica
0       0           1          0
1       0           1          0
2       0           1          0
3       0           0          1
4       0           0          1

In [130]:
svm_multi_array = svm_multi(X_test).values
svm_multi_array_recovery = np.argmax(svm_multi_array, axis=1).reshape(-1,1)

svm_multi_array_recovery

array([[1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [0],
       [2],
       [0],
       [1],
       [2],
       [0],
       [0],
       [2],
       [1],
       [1],
       [0],
       [1],
       [2],
       [2],
       [0],
       [2],
       [1],
       [1],
       [2],
       [0],
       [0],
       [2],
       [2],
       [1]], dtype=int64)

In [10]:
# Case 2 : One vs One SVM을 이 부분에 구현해주세요. 이것은 선택사항입니다! 

['versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica', 'virginica', 'setosa', 'virginica', 'setosa', 'versicolor', 'virginica', 'setosa', 'setosa', 'virginica', 'versicolor', 'versicolor', 'setosa', 'versicolor', 'virginica', 'virginica', 'setosa', 'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa', 'setosa', 'virginica', 'virginica', 'versicolor']


0.8666666666666667

In [139]:
# 그냥 원래 라이브러리가 제공하는 멀티클래스 SVM과 여러분이 구현한 multiclass SVM결과를 한 번 비교해주세요
from sklearn.model_selection import train_test_split #데이터셋 분리
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X, y, test_size=0.2, random_state=48)

svm_4 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_4.fit(X_train_2, y_train_2)
y_pred = svm_4.predict(X_test_2)

metrics.accuracy_score(y_test_2,y_pred)

0.8333333333333334

In [142]:
print(svm_4.predict(X_test_2))    # 원래 라이브러리가 제공하는 멀티클래스 SVM 이 분류한 값

['versicolor' 'versicolor' 'versicolor' 'virginica' 'virginica'
 'virginica' 'setosa' 'virginica' 'setosa' 'versicolor' 'virginica'
 'setosa' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'virginica' 'virginica' 'virginica' 'setosa' 'virginica' 'versicolor'
 'versicolor' 'virginica' 'setosa' 'setosa' 'virginica' 'virginica'
 'versicolor']
